import './components/dinamicHeight.js';
// import './components/sliders.js';
import './components/modals.js';
// import './components/acc.js';
// import './components/fancybox.js';
// import './components/mobile-menu.js';
// import './components/preloader.js';
import './components/codeForm.js';
import './components/initTel.js';
import './components/tabs.js';
import './components/chart.js';
import './components/checkbox.js';
import './components/simplebar.js';
import './components/global.js';
import './components/fundsMenu.js';
import './components/2faMenu.js';
